[project]
name = "algos"
version = "1.0.0"
description = "My algorithm studies."
authors = [
    {name = "Alexander Medeiros", email = "ajmed13@gmail.com"},
]
dependencies = []
requires-python = ">=3.8"
readme = "README.md"
license = {text = "MIT"}


[tool.pdm]
distribution = false
